#!/usr/bin/env bash
set -euo pipefail

if [[ "$PWD" != "/home/fb/src/paper/gazelleV1" ]]; then
  echo "Run this script from /home/fb/src/paper/gazelleV1" >&2
  exit 2
fi

mkdir -p /home/fb/src/paper/gazelleV1/AAAIResults/P05 /home/fb/src/paper/gazelleV1/AAAIResults/logs

/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention fixed_mean --model-label p05_fixed_mean --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_fixed_mean
/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention shuffle_previous_frame --model-label p05_shuffle_previous_frame --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_shuffle
/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention equal --model-label p05_equal --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_equal
/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention last_only --model-label p05_last_only --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_last_only
/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention shallow_deep --model-label p05_shallow_deep --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_shallow_deep
/home/fb/anaconda3/envs/py310/bin/python -u AAAIScripts/p05_inference_interventions.py --dataset vat --data-path /newhome/fb/dataset/videoattentiontarget --json-path /newhome/fb/dataset/videoattentiontarget/test_preprocessed.json --checkpoint /home/fb/src/paper/gazelleV1/experiments/train_vat_sasa_ggsf/2026-03-12_19-24-13/epoch_7.pt --intervention ggsf_identity --model-label p05_ggsf_identity --device cuda:0 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_ggsf_identity

/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_fixed_mean.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_fixed_mean
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_shuffle.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_shuffle
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_equal.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_equal
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_last_only.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_last_only
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_shallow_deep.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_shallow_deep
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P0/vat_spot_full.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_ggsf_identity.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/learned_vs_ggsf_identity
/home/fb/anaconda3/envs/py310/bin/python AAAIScripts/compare_failure_reports.py --reference-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_last_only.records.csv --candidate-records /home/fb/src/paper/gazelleV1/AAAIResults/P05/vat_shallow_deep.records.csv --bootstrap-iterations 2000 --seed 3106 --output-prefix /home/fb/src/paper/gazelleV1/AAAIResults/P05/last_only_vs_shallow_deep

echo "P0.5 complete: /home/fb/src/paper/gazelleV1/AAAIResults/P05"
